Name:           ros-hydro-sr-hand
Version:        1.3.5
Release:        0%{?dist}
Summary:        ROS sr_hand package

Group:          Development/Libraries
License:        GPL
URL:            http://www.shadowrobot.com
Source0:        %{name}-%{version}.tar.gz

Requires:       gazebo-devel
Requires:       ros-hydro-diagnostic-msgs
Requires:       ros-hydro-dynamic-reconfigure
Requires:       ros-hydro-gazebo-msgs
Requires:       ros-hydro-gazebo-ros
Requires:       ros-hydro-pr2-controllers-msgs
Requires:       ros-hydro-pr2-mechanism-msgs
Requires:       ros-hydro-robot-state-publisher
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-roslib
Requires:       ros-hydro-rospy
Requires:       ros-hydro-self-test
Requires:       ros-hydro-sensor-msgs
Requires:       ros-hydro-sr-robot-msgs
Requires:       ros-hydro-sr-utilities
Requires:       ros-hydro-std-msgs
Requires:       ros-hydro-std-srvs
Requires:       ros-hydro-urdf
BuildRequires:  gazebo-devel
BuildRequires:  gtest-devel
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-diagnostic-msgs
BuildRequires:  ros-hydro-dynamic-reconfigure
BuildRequires:  ros-hydro-gazebo-msgs
BuildRequires:  ros-hydro-pr2-controllers-msgs
BuildRequires:  ros-hydro-pr2-mechanism-msgs
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-roslib
BuildRequires:  ros-hydro-rospy
BuildRequires:  ros-hydro-rostest
BuildRequires:  ros-hydro-self-test
BuildRequires:  ros-hydro-sensor-msgs
BuildRequires:  ros-hydro-sr-robot-msgs
BuildRequires:  ros-hydro-sr-utilities
BuildRequires:  ros-hydro-std-msgs
BuildRequires:  ros-hydro-std-srvs
BuildRequires:  ros-hydro-urdf

%description
This is a ROS interface to the Shadow Robot's robotic hand. It contains both an
interface to the real hand (communicating via a CAN interface) and a simulated
version of the hand. It also contains an interface to Shadow Robot's muscle arm.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Mon Sep 22 2014 Shadow Robot's software team <software@shadowrobot.com> - 1.3.5-0
- Autogenerated by Bloom

* Fri Sep 19 2014 Shadow Robot's software team <software@shadowrobot.com> - 1.3.4-0
- Autogenerated by Bloom

