Name:           ros-hydro-sr-gazebo-plugins
Version:        1.3.5
Release:        2%{?dist}
Summary:        ROS sr_gazebo_plugins package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/pr2_gazebo_plugins
Source0:        %{name}-%{version}.tar.gz

Requires:       gazebo-devel
Requires:       ros-hydro-angles
Requires:       ros-hydro-diagnostic-msgs
Requires:       ros-hydro-diagnostic-updater
Requires:       ros-hydro-dynamic-reconfigure
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-nav-msgs
Requires:       ros-hydro-pr2-controller-manager
Requires:       ros-hydro-pr2-hardware-interface
Requires:       ros-hydro-pr2-mechanism-model
Requires:       ros-hydro-pr2-msgs
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-rospy
Requires:       ros-hydro-sensor-msgs
Requires:       ros-hydro-sr-hardware-interface
Requires:       ros-hydro-sr-self-test
Requires:       ros-hydro-std-msgs
Requires:       ros-hydro-urdf
Requires:       tinyxml-devel
BuildRequires:  gazebo-devel
BuildRequires:  ros-hydro-angles
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-cmake-modules
BuildRequires:  ros-hydro-diagnostic-msgs
BuildRequires:  ros-hydro-diagnostic-updater
BuildRequires:  ros-hydro-dynamic-reconfigure
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-nav-msgs
BuildRequires:  ros-hydro-pr2-controller-manager
BuildRequires:  ros-hydro-pr2-hardware-interface
BuildRequires:  ros-hydro-pr2-mechanism-model
BuildRequires:  ros-hydro-pr2-msgs
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-rospy
BuildRequires:  ros-hydro-sensor-msgs
BuildRequires:  ros-hydro-sr-hardware-interface
BuildRequires:  ros-hydro-sr-self-test
BuildRequires:  ros-hydro-std-msgs
BuildRequires:  ros-hydro-urdf
BuildRequires:  tinyxml-devel

%description
Gazebo Plugins for various Shadow Robot-specific sensors and actuators on the
robot.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Mon Sep 22 2014 Shadow Robot's software team <software@shadowrobot.com> - 1.3.5-2
- Autogenerated by Bloom

* Mon Sep 22 2014 Shadow Robot's software team <software@shadowrobot.com> - 1.3.5-1
- Autogenerated by Bloom

* Mon Sep 22 2014 Shadow Robot's software team <software@shadowrobot.com> - 1.3.5-0
- Autogenerated by Bloom

* Fri Sep 19 2014 Shadow Robot's software team <software@shadowrobot.com> - 1.3.4-0
- Autogenerated by Bloom

