Name:           ros-hydro-sr-mechanism-controllers
Version:        1.3.5
Release:        0%{?dist}
Summary:        ROS sr_mechanism_controllers package

Group:          Development/Libraries
License:        GPL
URL:            http://ros.org/wiki/sr_mechanism_controllers
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-actionlib
Requires:       ros-hydro-angles
Requires:       ros-hydro-control-toolbox
Requires:       ros-hydro-pluginlib
Requires:       ros-hydro-pr2-controller-interface
Requires:       ros-hydro-pr2-controllers-msgs
Requires:       ros-hydro-pr2-mechanism-controllers
Requires:       ros-hydro-pr2-mechanism-model
Requires:       ros-hydro-realtime-tools
Requires:       ros-hydro-robot-mechanism-controllers
Requires:       ros-hydro-rosconsole
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-sr-hardware-interface
Requires:       ros-hydro-sr-robot-msgs
Requires:       ros-hydro-sr-utilities
Requires:       ros-hydro-std-msgs
Requires:       ros-hydro-std-srvs
Requires:       ros-hydro-xmlrpcpp
BuildRequires:  gtest-devel
BuildRequires:  ros-hydro-actionlib
BuildRequires:  ros-hydro-angles
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-cmake-modules
BuildRequires:  ros-hydro-control-toolbox
BuildRequires:  ros-hydro-pluginlib
BuildRequires:  ros-hydro-pr2-controller-interface
BuildRequires:  ros-hydro-pr2-controllers-msgs
BuildRequires:  ros-hydro-pr2-mechanism-controllers
BuildRequires:  ros-hydro-pr2-mechanism-model
BuildRequires:  ros-hydro-realtime-tools
BuildRequires:  ros-hydro-robot-mechanism-controllers
BuildRequires:  ros-hydro-rosconsole
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-rostest
BuildRequires:  ros-hydro-sr-hardware-interface
BuildRequires:  ros-hydro-sr-robot-msgs
BuildRequires:  ros-hydro-sr-utilities
BuildRequires:  ros-hydro-std-msgs
BuildRequires:  ros-hydro-std-srvs
BuildRequires:  ros-hydro-xmlrpcpp
BuildRequires:  tinyxml-devel

%description
The sr_mechanism_controllers package contains different types of controllers for
the etherCAT hand:(fake) calibration controllers, position controllers, velocity
controllers, force controllers, ...

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Mon Sep 22 2014 Shadow Robot's software team <software@shadowrobot.com> - 1.3.5-0
- Autogenerated by Bloom

* Fri Sep 19 2014 Shadow Robot's software team <software@shadowrobot.com> - 1.3.4-0
- Autogenerated by Bloom

