Name:           ros-indigo-sr-mechanism-controllers
Version:        1.3.2
Release:        0%{?dist}
Summary:        ROS sr_mechanism_controllers package

Group:          Development/Libraries
License:        GPL
URL:            http://ros.org/wiki/sr_mechanism_controllers
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-actionlib
Requires:       ros-indigo-angles
Requires:       ros-indigo-control-msgs
Requires:       ros-indigo-control-toolbox
Requires:       ros-indigo-controller-interface
Requires:       ros-indigo-controller-manager-msgs
Requires:       ros-indigo-pluginlib
Requires:       ros-indigo-realtime-tools
Requires:       ros-indigo-ros-ethercat-model
Requires:       ros-indigo-rosconsole
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-sr-hardware-interface
Requires:       ros-indigo-sr-robot-msgs
Requires:       ros-indigo-sr-utilities
Requires:       ros-indigo-std-msgs
Requires:       ros-indigo-std-srvs
Requires:       ros-indigo-velocity-controllers
Requires:       ros-indigo-xmlrpcpp
BuildRequires:  gtest-devel
BuildRequires:  ros-indigo-actionlib
BuildRequires:  ros-indigo-angles
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-cmake-modules
BuildRequires:  ros-indigo-control-msgs
BuildRequires:  ros-indigo-control-toolbox
BuildRequires:  ros-indigo-controller-interface
BuildRequires:  ros-indigo-controller-manager-msgs
BuildRequires:  ros-indigo-pluginlib
BuildRequires:  ros-indigo-realtime-tools
BuildRequires:  ros-indigo-ros-ethercat-model
BuildRequires:  ros-indigo-rosconsole
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-rostest
BuildRequires:  ros-indigo-sr-hardware-interface
BuildRequires:  ros-indigo-sr-robot-msgs
BuildRequires:  ros-indigo-sr-utilities
BuildRequires:  ros-indigo-std-msgs
BuildRequires:  ros-indigo-std-srvs
BuildRequires:  ros-indigo-velocity-controllers
BuildRequires:  ros-indigo-xmlrpcpp
BuildRequires:  tinyxml-devel

%description
The sr_mechanism_controllers package contains different types of controllers for
the etherCAT hand:(fake) calibration controllers, position controllers, velocity
controllers, force controllers, ...

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Dec 21 2014 Shadow Robot's software team <software@shadowrobot.com> - 1.3.2-0
- Autogenerated by Bloom

